services:
    cortana:
        restart: always
        image: cortana
        container_name: cortana
        environment:
            - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
            - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
            - DROPBOX_TOKEN=${DROPBOX_TOKEN}
            - CORTANA_TOKEN=${CORTANA_TOKEN}
        labels:
          - com.centurylinklabs.watchtower.enable=false
